apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  selector:
    matchLabels:
      app: webapp-demo
    replicas: 3
template:
  metadata:
    name: webapp-demo
    namespace: webapp-example
    labels:
      app: webapp-demo
  spec:
    containers:
      - name: webapp-demo
        image: training/webapp
        ports:
          - containerPort: 5000
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "100Mi"
        command: ["python"]
        args: ["app.py"]
  ---
  apiVersion: v1
  kind: Service
  metadata:
    name: webapp-demo-lb
    namespace: webapp-example
    labels:
      run: webapp-demo
  spec:
    selector:
      app: webapp-demo
    type: LoadBalancer
    ports:
      - name: "http"
        port: 80
        targetPort: 5000
        protocol: "TCP"
